# Welcome to Jekyll!

# Website settings
title: Nick
description: 'Nikolaos Zioulis, an electrical and computer science engineer.'
keywords: Nikolaos Zioulis, Computer Vision, Graphics, Research & Development
baseurl:  
url: http://zokin.github.io  # url should be 'http://<github_username>.github.io'
#url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  # url should be '/static/assets/img/blog' as before

permalink: /:categories/:title

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Nick  # Be used at blog posts' author.
  first_name: Nikolaos  # Be used at index page about me section.
  last_name: Zioulis  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar_pastel.png  # upload your avatar at directory and edit it.
  github_username: zokin  # Leave blank if you don't have now
  linkedin_id:  # Leave blank if you don't have now
  facebook_username:   # Leave blank if you don't have now
  twitter_username:   # Leave blank if you don't have now
  email: nzioulis@gmail.com  # Leave blank if you don't have now
  cv: # /static/assets/pdf/landing/Bin_CV_en_cn.pdf  # A online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    #- name: fa-film
    #- name: icon-3dprint
    #- name: fa-eye
    - icon:
      name: icon-3dprint
      color: '#808080'
      #color: '#34CAAD'
    - icon:
      name: fa-eye
      color: '#808080'
      #color: '#0D317A'
    #- name: fa-camera
    #- name: icon-csharp
  skill_icon2:
    #- name: fa-code
    #- name: fa-desktop
    - icon:
      name: fa-code
      color: '#808080'
      #color: '#5637A7'
    - icon:
      name: fa-desktop
      color: '#808080'
      #color: '#098B92'
    #- name: fa-terminal
    #- name: icon-cplusplus
  desc: I am an engineer working on the verge of computer graphics, computer vision and software engineering. My research interests and working experience are mainly in 3D computer vision and graphics, targeting innovative applications for augmented and virtual reality, including 3D human reconstruction and applied in tele-immersion / holoportation settings. Seeing the great potential of modern artificial intelligence, i am also indulging myself into machine (deep) learning techniques. # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  #name: Homepage
  #public_key: V6cXAp2zapMpq1HWh5oYwPYJidQJzWn7pzHJeKcZPCq1DkbQftxp7rcg0jze4Spo

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
   id: # UA-62083650-1

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
